name: Cleanup

on:
  issues:
    types: [edited]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' && contains(github.event.issue.labels, 'code-analyzed')
    steps:
      - name: Cleanup workspace
        run: |
          echo "🧹 Analysis completed - workspace will be automatically cleaned up"

      - name: Close issue if analysis succeeded
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
